// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: treedb.proto

package apiv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReadOp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entry         string                 `protobuf:"bytes,1,opt,name=entry,proto3" json:"entry,omitempty"`
	Keys          []string               `protobuf:"bytes,2,rep,name=keys,proto3" json:"keys,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadOp) Reset() {
	*x = ReadOp{}
	mi := &file_treedb_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadOp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadOp) ProtoMessage() {}

func (x *ReadOp) ProtoReflect() protoreflect.Message {
	mi := &file_treedb_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadOp.ProtoReflect.Descriptor instead.
func (*ReadOp) Descriptor() ([]byte, []int) {
	return file_treedb_proto_rawDescGZIP(), []int{0}
}

func (x *ReadOp) GetEntry() string {
	if x != nil {
		return x.Entry
	}
	return ""
}

func (x *ReadOp) GetKeys() []string {
	if x != nil {
		return x.Keys
	}
	return nil
}

type ReadOpResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entry         string                 `protobuf:"bytes,1,opt,name=entry,proto3" json:"entry,omitempty"`
	Exists        bool                   `protobuf:"varint,2,opt,name=exists,proto3" json:"exists,omitempty"`
	KeyToValue    map[string]string      `protobuf:"bytes,3,rep,name=key_to_value,json=keyToValue,proto3" json:"key_to_value,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadOpResult) Reset() {
	*x = ReadOpResult{}
	mi := &file_treedb_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadOpResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadOpResult) ProtoMessage() {}

func (x *ReadOpResult) ProtoReflect() protoreflect.Message {
	mi := &file_treedb_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadOpResult.ProtoReflect.Descriptor instead.
func (*ReadOpResult) Descriptor() ([]byte, []int) {
	return file_treedb_proto_rawDescGZIP(), []int{1}
}

func (x *ReadOpResult) GetEntry() string {
	if x != nil {
		return x.Entry
	}
	return ""
}

func (x *ReadOpResult) GetExists() bool {
	if x != nil {
		return x.Exists
	}
	return false
}

func (x *ReadOpResult) GetKeyToValue() map[string]string {
	if x != nil {
		return x.KeyToValue
	}
	return nil
}

type ReadBatchReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ops           []*ReadOp              `protobuf:"bytes,1,rep,name=ops,proto3" json:"ops,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadBatchReq) Reset() {
	*x = ReadBatchReq{}
	mi := &file_treedb_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadBatchReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadBatchReq) ProtoMessage() {}

func (x *ReadBatchReq) ProtoReflect() protoreflect.Message {
	mi := &file_treedb_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadBatchReq.ProtoReflect.Descriptor instead.
func (*ReadBatchReq) Descriptor() ([]byte, []int) {
	return file_treedb_proto_rawDescGZIP(), []int{2}
}

func (x *ReadBatchReq) GetOps() []*ReadOp {
	if x != nil {
		return x.Ops
	}
	return nil
}

type ReadBatchResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*ReadOpResult        `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadBatchResp) Reset() {
	*x = ReadBatchResp{}
	mi := &file_treedb_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadBatchResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadBatchResp) ProtoMessage() {}

func (x *ReadBatchResp) ProtoReflect() protoreflect.Message {
	mi := &file_treedb_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadBatchResp.ProtoReflect.Descriptor instead.
func (*ReadBatchResp) Descriptor() ([]byte, []int) {
	return file_treedb_proto_rawDescGZIP(), []int{3}
}

func (x *ReadBatchResp) GetResults() []*ReadOpResult {
	if x != nil {
		return x.Results
	}
	return nil
}

type WriteActionCreate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteActionCreate) Reset() {
	*x = WriteActionCreate{}
	mi := &file_treedb_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteActionCreate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteActionCreate) ProtoMessage() {}

func (x *WriteActionCreate) ProtoReflect() protoreflect.Message {
	mi := &file_treedb_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteActionCreate.ProtoReflect.Descriptor instead.
func (*WriteActionCreate) Descriptor() ([]byte, []int) {
	return file_treedb_proto_rawDescGZIP(), []int{4}
}

func (x *WriteActionCreate) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type WriteActionDelete struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteActionDelete) Reset() {
	*x = WriteActionDelete{}
	mi := &file_treedb_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteActionDelete) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteActionDelete) ProtoMessage() {}

func (x *WriteActionDelete) ProtoReflect() protoreflect.Message {
	mi := &file_treedb_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteActionDelete.ProtoReflect.Descriptor instead.
func (*WriteActionDelete) Descriptor() ([]byte, []int) {
	return file_treedb_proto_rawDescGZIP(), []int{5}
}

func (x *WriteActionDelete) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type WriteActionUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PutKeyToValue map[string]string      `protobuf:"bytes,1,rep,name=put_key_to_value,json=putKeyToValue,proto3" json:"put_key_to_value,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	DeleteKeys    []string               `protobuf:"bytes,2,rep,name=delete_keys,json=deleteKeys,proto3" json:"delete_keys,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteActionUpdate) Reset() {
	*x = WriteActionUpdate{}
	mi := &file_treedb_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteActionUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteActionUpdate) ProtoMessage() {}

func (x *WriteActionUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_treedb_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteActionUpdate.ProtoReflect.Descriptor instead.
func (*WriteActionUpdate) Descriptor() ([]byte, []int) {
	return file_treedb_proto_rawDescGZIP(), []int{6}
}

func (x *WriteActionUpdate) GetPutKeyToValue() map[string]string {
	if x != nil {
		return x.PutKeyToValue
	}
	return nil
}

func (x *WriteActionUpdate) GetDeleteKeys() []string {
	if x != nil {
		return x.DeleteKeys
	}
	return nil
}

type WriteOp struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Entry string                 `protobuf:"bytes,1,opt,name=entry,proto3" json:"entry,omitempty"`
	// Types that are valid to be assigned to Action:
	//
	//	*WriteOp_Create
	//	*WriteOp_Delete
	//	*WriteOp_Update
	Action        isWriteOp_Action `protobuf_oneof:"action"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteOp) Reset() {
	*x = WriteOp{}
	mi := &file_treedb_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteOp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteOp) ProtoMessage() {}

func (x *WriteOp) ProtoReflect() protoreflect.Message {
	mi := &file_treedb_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteOp.ProtoReflect.Descriptor instead.
func (*WriteOp) Descriptor() ([]byte, []int) {
	return file_treedb_proto_rawDescGZIP(), []int{7}
}

func (x *WriteOp) GetEntry() string {
	if x != nil {
		return x.Entry
	}
	return ""
}

func (x *WriteOp) GetAction() isWriteOp_Action {
	if x != nil {
		return x.Action
	}
	return nil
}

func (x *WriteOp) GetCreate() *WriteActionCreate {
	if x != nil {
		if x, ok := x.Action.(*WriteOp_Create); ok {
			return x.Create
		}
	}
	return nil
}

func (x *WriteOp) GetDelete() *WriteActionDelete {
	if x != nil {
		if x, ok := x.Action.(*WriteOp_Delete); ok {
			return x.Delete
		}
	}
	return nil
}

func (x *WriteOp) GetUpdate() *WriteActionUpdate {
	if x != nil {
		if x, ok := x.Action.(*WriteOp_Update); ok {
			return x.Update
		}
	}
	return nil
}

type isWriteOp_Action interface {
	isWriteOp_Action()
}

type WriteOp_Create struct {
	Create *WriteActionCreate `protobuf:"bytes,2,opt,name=create,proto3,oneof"`
}

type WriteOp_Delete struct {
	Delete *WriteActionDelete `protobuf:"bytes,3,opt,name=delete,proto3,oneof"`
}

type WriteOp_Update struct {
	Update *WriteActionUpdate `protobuf:"bytes,4,opt,name=update,proto3,oneof"`
}

func (*WriteOp_Create) isWriteOp_Action() {}

func (*WriteOp_Delete) isWriteOp_Action() {}

func (*WriteOp_Update) isWriteOp_Action() {}

type WriteBatchReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ops           []*WriteOp             `protobuf:"bytes,1,rep,name=ops,proto3" json:"ops,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteBatchReq) Reset() {
	*x = WriteBatchReq{}
	mi := &file_treedb_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteBatchReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteBatchReq) ProtoMessage() {}

func (x *WriteBatchReq) ProtoReflect() protoreflect.Message {
	mi := &file_treedb_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteBatchReq.ProtoReflect.Descriptor instead.
func (*WriteBatchReq) Descriptor() ([]byte, []int) {
	return file_treedb_proto_rawDescGZIP(), []int{8}
}

func (x *WriteBatchReq) GetOps() []*WriteOp {
	if x != nil {
		return x.Ops
	}
	return nil
}

type WriteBatchResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteBatchResp) Reset() {
	*x = WriteBatchResp{}
	mi := &file_treedb_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteBatchResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteBatchResp) ProtoMessage() {}

func (x *WriteBatchResp) ProtoReflect() protoreflect.Message {
	mi := &file_treedb_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteBatchResp.ProtoReflect.Descriptor instead.
func (*WriteBatchResp) Descriptor() ([]byte, []int) {
	return file_treedb_proto_rawDescGZIP(), []int{9}
}

type WatchNotifyChReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Notifier      string                 `protobuf:"bytes,1,opt,name=notifier,proto3" json:"notifier,omitempty"`
	Entries       []string               `protobuf:"bytes,2,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchNotifyChReq) Reset() {
	*x = WatchNotifyChReq{}
	mi := &file_treedb_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchNotifyChReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchNotifyChReq) ProtoMessage() {}

func (x *WatchNotifyChReq) ProtoReflect() protoreflect.Message {
	mi := &file_treedb_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchNotifyChReq.ProtoReflect.Descriptor instead.
func (*WatchNotifyChReq) Descriptor() ([]byte, []int) {
	return file_treedb_proto_rawDescGZIP(), []int{10}
}

func (x *WatchNotifyChReq) GetNotifier() string {
	if x != nil {
		return x.Notifier
	}
	return ""
}

func (x *WatchNotifyChReq) GetEntries() []string {
	if x != nil {
		return x.Entries
	}
	return nil
}

type WatchNotifyChResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        *ReadOpResult          `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchNotifyChResp) Reset() {
	*x = WatchNotifyChResp{}
	mi := &file_treedb_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchNotifyChResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchNotifyChResp) ProtoMessage() {}

func (x *WatchNotifyChResp) ProtoReflect() protoreflect.Message {
	mi := &file_treedb_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchNotifyChResp.ProtoReflect.Descriptor instead.
func (*WatchNotifyChResp) Descriptor() ([]byte, []int) {
	return file_treedb_proto_rawDescGZIP(), []int{11}
}

func (x *WatchNotifyChResp) GetResult() *ReadOpResult {
	if x != nil {
		return x.Result
	}
	return nil
}

type CloseNotifyChReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Notifier      string                 `protobuf:"bytes,1,opt,name=notifier,proto3" json:"notifier,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseNotifyChReq) Reset() {
	*x = CloseNotifyChReq{}
	mi := &file_treedb_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseNotifyChReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseNotifyChReq) ProtoMessage() {}

func (x *CloseNotifyChReq) ProtoReflect() protoreflect.Message {
	mi := &file_treedb_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseNotifyChReq.ProtoReflect.Descriptor instead.
func (*CloseNotifyChReq) Descriptor() ([]byte, []int) {
	return file_treedb_proto_rawDescGZIP(), []int{12}
}

func (x *CloseNotifyChReq) GetNotifier() string {
	if x != nil {
		return x.Notifier
	}
	return ""
}

type CloseNotifyChResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseNotifyChResp) Reset() {
	*x = CloseNotifyChResp{}
	mi := &file_treedb_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseNotifyChResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseNotifyChResp) ProtoMessage() {}

func (x *CloseNotifyChResp) ProtoReflect() protoreflect.Message {
	mi := &file_treedb_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseNotifyChResp.ProtoReflect.Descriptor instead.
func (*CloseNotifyChResp) Descriptor() ([]byte, []int) {
	return file_treedb_proto_rawDescGZIP(), []int{13}
}

var File_treedb_proto protoreflect.FileDescriptor

const file_treedb_proto_rawDesc = "" +
	"\n" +
	"\ftreedb.proto\x12\ttreedb.v1\"2\n" +
	"\x06ReadOp\x12\x14\n" +
	"\x05entry\x18\x01 \x01(\tR\x05entry\x12\x12\n" +
	"\x04keys\x18\x02 \x03(\tR\x04keys\"\xc6\x01\n" +
	"\fReadOpResult\x12\x14\n" +
	"\x05entry\x18\x01 \x01(\tR\x05entry\x12\x16\n" +
	"\x06exists\x18\x02 \x01(\bR\x06exists\x12I\n" +
	"\fkey_to_value\x18\x03 \x03(\v2'.treedb.v1.ReadOpResult.KeyToValueEntryR\n" +
	"keyToValue\x1a=\n" +
	"\x0fKeyToValueEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"3\n" +
	"\fReadBatchReq\x12#\n" +
	"\x03ops\x18\x01 \x03(\v2\x11.treedb.v1.ReadOpR\x03ops\"B\n" +
	"\rReadBatchResp\x121\n" +
	"\aresults\x18\x01 \x03(\v2\x17.treedb.v1.ReadOpResultR\aresults\"'\n" +
	"\x11WriteActionCreate\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"'\n" +
	"\x11WriteActionDelete\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\xd0\x01\n" +
	"\x11WriteActionUpdate\x12X\n" +
	"\x10put_key_to_value\x18\x01 \x03(\v2/.treedb.v1.WriteActionUpdate.PutKeyToValueEntryR\rputKeyToValue\x12\x1f\n" +
	"\vdelete_keys\x18\x02 \x03(\tR\n" +
	"deleteKeys\x1a@\n" +
	"\x12PutKeyToValueEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xd1\x01\n" +
	"\aWriteOp\x12\x14\n" +
	"\x05entry\x18\x01 \x01(\tR\x05entry\x126\n" +
	"\x06create\x18\x02 \x01(\v2\x1c.treedb.v1.WriteActionCreateH\x00R\x06create\x126\n" +
	"\x06delete\x18\x03 \x01(\v2\x1c.treedb.v1.WriteActionDeleteH\x00R\x06delete\x126\n" +
	"\x06update\x18\x04 \x01(\v2\x1c.treedb.v1.WriteActionUpdateH\x00R\x06updateB\b\n" +
	"\x06action\"5\n" +
	"\rWriteBatchReq\x12$\n" +
	"\x03ops\x18\x01 \x03(\v2\x12.treedb.v1.WriteOpR\x03ops\"\x10\n" +
	"\x0eWriteBatchResp\"H\n" +
	"\x10WatchNotifyChReq\x12\x1a\n" +
	"\bnotifier\x18\x01 \x01(\tR\bnotifier\x12\x18\n" +
	"\aentries\x18\x02 \x03(\tR\aentries\"D\n" +
	"\x11WatchNotifyChResp\x12/\n" +
	"\x06result\x18\x01 \x01(\v2\x17.treedb.v1.ReadOpResultR\x06result\".\n" +
	"\x10CloseNotifyChReq\x12\x1a\n" +
	"\bnotifier\x18\x01 \x01(\tR\bnotifier\"\x13\n" +
	"\x11CloseNotifyChResp2\xa5\x02\n" +
	"\x06TreeDB\x12>\n" +
	"\tReadBatch\x12\x17.treedb.v1.ReadBatchReq\x1a\x18.treedb.v1.ReadBatchResp\x12A\n" +
	"\n" +
	"WriteBatch\x12\x18.treedb.v1.WriteBatchReq\x1a\x19.treedb.v1.WriteBatchResp\x12L\n" +
	"\rWatchNotifyCh\x12\x1b.treedb.v1.WatchNotifyChReq\x1a\x1c.treedb.v1.WatchNotifyChResp0\x01\x12J\n" +
	"\rCloseNotifyCh\x12\x1b.treedb.v1.CloseNotifyChReq\x1a\x1c.treedb.v1.CloseNotifyChRespB\tZ\a.;apiv1b\x06proto3"

var (
	file_treedb_proto_rawDescOnce sync.Once
	file_treedb_proto_rawDescData []byte
)

func file_treedb_proto_rawDescGZIP() []byte {
	file_treedb_proto_rawDescOnce.Do(func() {
		file_treedb_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_treedb_proto_rawDesc), len(file_treedb_proto_rawDesc)))
	})
	return file_treedb_proto_rawDescData
}

var file_treedb_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_treedb_proto_goTypes = []any{
	(*ReadOp)(nil),            // 0: treedb.v1.ReadOp
	(*ReadOpResult)(nil),      // 1: treedb.v1.ReadOpResult
	(*ReadBatchReq)(nil),      // 2: treedb.v1.ReadBatchReq
	(*ReadBatchResp)(nil),     // 3: treedb.v1.ReadBatchResp
	(*WriteActionCreate)(nil), // 4: treedb.v1.WriteActionCreate
	(*WriteActionDelete)(nil), // 5: treedb.v1.WriteActionDelete
	(*WriteActionUpdate)(nil), // 6: treedb.v1.WriteActionUpdate
	(*WriteOp)(nil),           // 7: treedb.v1.WriteOp
	(*WriteBatchReq)(nil),     // 8: treedb.v1.WriteBatchReq
	(*WriteBatchResp)(nil),    // 9: treedb.v1.WriteBatchResp
	(*WatchNotifyChReq)(nil),  // 10: treedb.v1.WatchNotifyChReq
	(*WatchNotifyChResp)(nil), // 11: treedb.v1.WatchNotifyChResp
	(*CloseNotifyChReq)(nil),  // 12: treedb.v1.CloseNotifyChReq
	(*CloseNotifyChResp)(nil), // 13: treedb.v1.CloseNotifyChResp
	nil,                       // 14: treedb.v1.ReadOpResult.KeyToValueEntry
	nil,                       // 15: treedb.v1.WriteActionUpdate.PutKeyToValueEntry
}
var file_treedb_proto_depIdxs = []int32{
	14, // 0: treedb.v1.ReadOpResult.key_to_value:type_name -> treedb.v1.ReadOpResult.KeyToValueEntry
	0,  // 1: treedb.v1.ReadBatchReq.ops:type_name -> treedb.v1.ReadOp
	1,  // 2: treedb.v1.ReadBatchResp.results:type_name -> treedb.v1.ReadOpResult
	15, // 3: treedb.v1.WriteActionUpdate.put_key_to_value:type_name -> treedb.v1.WriteActionUpdate.PutKeyToValueEntry
	4,  // 4: treedb.v1.WriteOp.create:type_name -> treedb.v1.WriteActionCreate
	5,  // 5: treedb.v1.WriteOp.delete:type_name -> treedb.v1.WriteActionDelete
	6,  // 6: treedb.v1.WriteOp.update:type_name -> treedb.v1.WriteActionUpdate
	7,  // 7: treedb.v1.WriteBatchReq.ops:type_name -> treedb.v1.WriteOp
	1,  // 8: treedb.v1.WatchNotifyChResp.result:type_name -> treedb.v1.ReadOpResult
	2,  // 9: treedb.v1.TreeDB.ReadBatch:input_type -> treedb.v1.ReadBatchReq
	8,  // 10: treedb.v1.TreeDB.WriteBatch:input_type -> treedb.v1.WriteBatchReq
	10, // 11: treedb.v1.TreeDB.WatchNotifyCh:input_type -> treedb.v1.WatchNotifyChReq
	12, // 12: treedb.v1.TreeDB.CloseNotifyCh:input_type -> treedb.v1.CloseNotifyChReq
	3,  // 13: treedb.v1.TreeDB.ReadBatch:output_type -> treedb.v1.ReadBatchResp
	9,  // 14: treedb.v1.TreeDB.WriteBatch:output_type -> treedb.v1.WriteBatchResp
	11, // 15: treedb.v1.TreeDB.WatchNotifyCh:output_type -> treedb.v1.WatchNotifyChResp
	13, // 16: treedb.v1.TreeDB.CloseNotifyCh:output_type -> treedb.v1.CloseNotifyChResp
	13, // [13:17] is the sub-list for method output_type
	9,  // [9:13] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_treedb_proto_init() }
func file_treedb_proto_init() {
	if File_treedb_proto != nil {
		return
	}
	file_treedb_proto_msgTypes[7].OneofWrappers = []any{
		(*WriteOp_Create)(nil),
		(*WriteOp_Delete)(nil),
		(*WriteOp_Update)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_treedb_proto_rawDesc), len(file_treedb_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_treedb_proto_goTypes,
		DependencyIndexes: file_treedb_proto_depIdxs,
		MessageInfos:      file_treedb_proto_msgTypes,
	}.Build()
	File_treedb_proto = out.File
	file_treedb_proto_goTypes = nil
	file_treedb_proto_depIdxs = nil
}
