// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.31.1
// source: treedb.proto

package apiv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TreeDB_ReadBatch_FullMethodName     = "/treedb.v1.TreeDB/ReadBatch"
	TreeDB_WriteBatch_FullMethodName    = "/treedb.v1.TreeDB/WriteBatch"
	TreeDB_WatchNotifyCh_FullMethodName = "/treedb.v1.TreeDB/WatchNotifyCh"
	TreeDB_CloseNotifyCh_FullMethodName = "/treedb.v1.TreeDB/CloseNotifyCh"
)

// TreeDBClient is the client API for TreeDB service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TreeDBClient interface {
	ReadBatch(ctx context.Context, in *ReadBatchReq, opts ...grpc.CallOption) (*ReadBatchResp, error)
	WriteBatch(ctx context.Context, in *WriteBatchReq, opts ...grpc.CallOption) (*WriteBatchResp, error)
	WatchNotifyCh(ctx context.Context, in *WatchNotifyChReq, opts ...grpc.CallOption) (grpc.ServerStreamingClient[WatchNotifyChResp], error)
	CloseNotifyCh(ctx context.Context, in *CloseNotifyChReq, opts ...grpc.CallOption) (*CloseNotifyChResp, error)
}

type treeDBClient struct {
	cc grpc.ClientConnInterface
}

func NewTreeDBClient(cc grpc.ClientConnInterface) TreeDBClient {
	return &treeDBClient{cc}
}

func (c *treeDBClient) ReadBatch(ctx context.Context, in *ReadBatchReq, opts ...grpc.CallOption) (*ReadBatchResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReadBatchResp)
	err := c.cc.Invoke(ctx, TreeDB_ReadBatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *treeDBClient) WriteBatch(ctx context.Context, in *WriteBatchReq, opts ...grpc.CallOption) (*WriteBatchResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WriteBatchResp)
	err := c.cc.Invoke(ctx, TreeDB_WriteBatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *treeDBClient) WatchNotifyCh(ctx context.Context, in *WatchNotifyChReq, opts ...grpc.CallOption) (grpc.ServerStreamingClient[WatchNotifyChResp], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TreeDB_ServiceDesc.Streams[0], TreeDB_WatchNotifyCh_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchNotifyChReq, WatchNotifyChResp]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TreeDB_WatchNotifyChClient = grpc.ServerStreamingClient[WatchNotifyChResp]

func (c *treeDBClient) CloseNotifyCh(ctx context.Context, in *CloseNotifyChReq, opts ...grpc.CallOption) (*CloseNotifyChResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CloseNotifyChResp)
	err := c.cc.Invoke(ctx, TreeDB_CloseNotifyCh_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TreeDBServer is the server API for TreeDB service.
// All implementations must embed UnimplementedTreeDBServer
// for forward compatibility.
type TreeDBServer interface {
	ReadBatch(context.Context, *ReadBatchReq) (*ReadBatchResp, error)
	WriteBatch(context.Context, *WriteBatchReq) (*WriteBatchResp, error)
	WatchNotifyCh(*WatchNotifyChReq, grpc.ServerStreamingServer[WatchNotifyChResp]) error
	CloseNotifyCh(context.Context, *CloseNotifyChReq) (*CloseNotifyChResp, error)
	mustEmbedUnimplementedTreeDBServer()
}

// UnimplementedTreeDBServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTreeDBServer struct{}

func (UnimplementedTreeDBServer) ReadBatch(context.Context, *ReadBatchReq) (*ReadBatchResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadBatch not implemented")
}
func (UnimplementedTreeDBServer) WriteBatch(context.Context, *WriteBatchReq) (*WriteBatchResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WriteBatch not implemented")
}
func (UnimplementedTreeDBServer) WatchNotifyCh(*WatchNotifyChReq, grpc.ServerStreamingServer[WatchNotifyChResp]) error {
	return status.Errorf(codes.Unimplemented, "method WatchNotifyCh not implemented")
}
func (UnimplementedTreeDBServer) CloseNotifyCh(context.Context, *CloseNotifyChReq) (*CloseNotifyChResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CloseNotifyCh not implemented")
}
func (UnimplementedTreeDBServer) mustEmbedUnimplementedTreeDBServer() {}
func (UnimplementedTreeDBServer) testEmbeddedByValue()                {}

// UnsafeTreeDBServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TreeDBServer will
// result in compilation errors.
type UnsafeTreeDBServer interface {
	mustEmbedUnimplementedTreeDBServer()
}

func RegisterTreeDBServer(s grpc.ServiceRegistrar, srv TreeDBServer) {
	// If the following call pancis, it indicates UnimplementedTreeDBServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TreeDB_ServiceDesc, srv)
}

func _TreeDB_ReadBatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadBatchReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TreeDBServer).ReadBatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TreeDB_ReadBatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TreeDBServer).ReadBatch(ctx, req.(*ReadBatchReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _TreeDB_WriteBatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WriteBatchReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TreeDBServer).WriteBatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TreeDB_WriteBatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TreeDBServer).WriteBatch(ctx, req.(*WriteBatchReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _TreeDB_WatchNotifyCh_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchNotifyChReq)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TreeDBServer).WatchNotifyCh(m, &grpc.GenericServerStream[WatchNotifyChReq, WatchNotifyChResp]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TreeDB_WatchNotifyChServer = grpc.ServerStreamingServer[WatchNotifyChResp]

func _TreeDB_CloseNotifyCh_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CloseNotifyChReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TreeDBServer).CloseNotifyCh(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TreeDB_CloseNotifyCh_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TreeDBServer).CloseNotifyCh(ctx, req.(*CloseNotifyChReq))
	}
	return interceptor(ctx, in, info, handler)
}

// TreeDB_ServiceDesc is the grpc.ServiceDesc for TreeDB service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TreeDB_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "treedb.v1.TreeDB",
	HandlerType: (*TreeDBServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReadBatch",
			Handler:    _TreeDB_ReadBatch_Handler,
		},
		{
			MethodName: "WriteBatch",
			Handler:    _TreeDB_WriteBatch_Handler,
		},
		{
			MethodName: "CloseNotifyCh",
			Handler:    _TreeDB_CloseNotifyCh_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WatchNotifyCh",
			Handler:       _TreeDB_WatchNotifyCh_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "treedb.proto",
}
